Pia 2966 injecting bottom bar
gini/gini-mobile-android pull request #124
Opened 2022-11-16 16:00 UTC by AdnanYupi

PIA 2966 

Bottom bar injected into review screen:
Note: check injection of loading indicator into review bottom bar

2022-11-16 16:35 UTC, a-szotyori reviewed
I think we need to refine the adapter a bit to let clients show loading indicators any way they want to.

2022-11-16 16:35 UTC, a-szotyori commented on capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/view/ReviewNavigationBarBottomAdapter.kt
> +interface ReviewNavigationBarBottomAdapter: InjectedViewAdapter {
[Suggestion] We can make this interface more abstract. We don't have to tell clients how to show the loading indicator. We can simply declare two methods: `showLoadingIndicator()` and `hideLoadingIndicator()`. In the default implementation we can then use the `OnButtonLoadingIndicatorAdapter` (oh, we have a dependency on PR #117).

Also renaming `onButtonStatus()` to `setContinueButtonEnabled(enabled: Boolean)` makes it clearer what should be done when implementing the interface.

Generally the interface method names should follow the imperative mood to tell clients what we want them to do in each method.

In summary here is my proposal for the interface:
```
interface ReviewNavigationBarBottomAdapter: InjectedViewAdapter {

    fun setOnContinueButtonClickListener(clickListener: View.OnClickListener)

    fun setOnAddPageButtonClickListener(clickListener: View.OnClickListener)

    fun setAddPageButtonVisibility(visibility: Int)

    fun setContinueButtonEnabled(enabled: Boolean)

    fun showLoadingIndicator()

    fun hideLoadingIndicator()
}
```

2022-11-17 16:02 UTC, a-szotyori requested changes
Thank you for the changes! Sorry for being picky with the method names. They are part of the SDK's public API and we need to follow the same naming conventions in all the adapter interfaces.

2022-11-17 16:02 UTC, a-szotyori commented on capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/view/ReviewNavigationBarBottomAdapter.kt
>      fun onAddPageClickListener(clickListener: View.OnClickListener)
[Request] Please rename to `setOnAddPageButtonClickListener`.

2022-11-17 16:02 UTC, a-szotyori commented on capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/view/ReviewNavigationBarBottomAdapter.kt
>      fun onAddPageVisible(visibility: Int)
[Request] Please rename to `setAddPageButtonVisibility`.

2022-11-17 19:10 UTC, AdnanYupi commented on capture-sdk/sdk/src/main/java/net/gini/android/capture/review/multipage/view/ReviewNavigationBarBottomAdapter.kt
>      fun onContinueClickListener(clickListener: View.OnClickListener)
No worries all good 👍

2022-11-18 09:45 UTC, a-szotyori approved these changes
Thank you!

2022-11-18 09:49 UTC, merged