Pia 3318 error screen bottom bar
gini/gini-mobile-android pull request #142
Opened 2022-12-01 10:04 UTC by AdnanYupi

- injected bottom bar 

PIA 3318

2022-12-05 14:31 UTC, llevente approved these changes

2022-12-07 19:05 UTC, a-szotyori requested changes
Nice, but the error screen should have its own dedicated bottom navigation bar adapter as well and not reuse the one from the help screen.

2022-12-07 19:07 UTC, AdnanYupi commented on capture-sdk/sdk/src/main/java/net/gini/android/capture/error/ErrorActivity.kt
> +            val bottomBarContainer = findViewById<InjectedViewContainer<HelpNavigationBarBottomAdapter>>(R.id.gc_injected_navigation_bar_container_bottom)
@a-szotyori that is what I actually wanted to ask but forgot :D

2022-12-08 09:07 UTC, a-szotyori approved these changes
Thank you!

2022-12-08 14:46 UTC, merged