feat(capture-sdk):
gini/gini-mobile-android pull request #161
Opened 2022-12-20 08:43 UTC by AdnanYupi

- only qr code scanning integration documentation

PIA-2977

2022-12-21 13:40 UTC, zladzeyka requested changes
👍🏻 Good job.
Just 2 suggestions from my side.

2022-12-21 13:40 UTC, zladzeyka commented on capture-sdk/sdk/src/doc/source/features.rst
> +The app supports QR code only scanning. To enable this feature simply pass ``true`` to ``GiniCapture.Builder.setOnlyQRCodeScanning``.
```suggestion
The app supports QR code only scanning mode. To enable this feature simply pass ``true`` to ``GiniCapture.Builder.setOnlyQRCodeScanning``.
```

2022-12-21 13:40 UTC, zladzeyka commented on capture-sdk/sdk/src/doc/source/features.rst
> +When enabled this feature removes all UI elements related to taking picture from the Camera screen and leaves only QR code related UI elements.
```suggestion
Enabling this feature removes all UI elements related to taking pictures from the Camera screen and leaves only QR code-related UI elements.
```

2022-12-22 09:29 UTC, zladzeyka approved these changes
👏🏻🎉😊

2023-01-04 14:09 UTC, llevente approved these changes

2023-01-05 07:08 UTC, merged