Pia 2988 analysis ref docs
gini/gini-mobile-android pull request #171
Opened 2023-01-05 08:34 UTC by llevente

2023-01-05 10:21 UTC, zladzeyka requested changes
Looks good 👍 😊
I have a few tiny notes only.

2023-01-05 10:21 UTC, zladzeyka commented on capture-sdk/sdk/src/main/java/net/gini/android/capture/analysis/AnalysisActivity.java
> + * <p> For images only the activity indicator and activity indicator message is shown without preview
[Suggestion] Maybe `.` is missing?

2023-01-05 10:21 UTC, zladzeyka commented on capture-sdk/sdk/src/main/java/net/gini/android/capture/analysis/AnalysisHintsAnimator.java
> - * Created by Alpar Szotyori on 09.05.2019.
[Clarification] Did you agree with Alpar to remove copyright and keep only `Internal use only`?

2023-01-10 17:30 UTC, a-szotyori requested changes
Thank you and there are some minor things only.

2023-01-10 17:30 UTC, a-szotyori commented on capture-sdk/sdk/src/main/java/net/gini/android/capture/analysis/AnalysisActivity.java
> + * instead by overriding the string resource named {@code gc_analysis_activity_indicator_message}.
[Request] You can replace this whole javadoc for AnalysisActivity with `Internal use only`. It's not part of the public API anymore.

Sorry that I wasn't able to tell you that earlier. 🙈

2023-01-10 17:30 UTC, a-szotyori commented on capture-sdk/sdk/src/main/java/net/gini/android/capture/analysis/AnalysisScreenPresenter.java
> + * Internal use only
[Request] We should keep the copyright section and add the `internal use only` below it in a separate javadoc like you did for AnalysisHintsAnimator.

2023-01-11 11:38 UTC, a-szotyori approved these changes

2023-01-12 07:48 UTC, merged