Docs for predictive back gesture - 3.x.x
gini/gini-mobile-android pull request #305
Opened 2023-05-09 16:39 UTC by a-szotyori

2023-05-11 15:13 UTC, zladzeyka approved these changes
Looks good!

2023-05-11 15:19 UTC, zladzeyka requested changes
[Clarification] Could you please confirm that  `Content type: Getting started` - we are inside the integration guide?

2023-05-12 07:00 UTC, a-szotyori commented
@zladzeyka I used the `content type` of `getting started` according to the book `Docs for Developers` because our integration guides fall more into the `getting started` category. The `getting started` category is for guiding users through first impressions and first-time user experience. In our new structure ([miro](https://miro.com/app/board/uXjVPrudthM=/)) we moved our integration guide content into the "getting started" section.

I will update the line to:
`Content type: Getting started - as defined in the Docs for Developers book`

2023-05-12 15:01 UTC, zladzeyka approved these changes

2023-05-12 15:01 UTC, zladzeyka approved these changes

2023-05-12 15:37 UTC, merged