feature(bank-sdk): Skonto. Amounts validation message
gini/gini-mobile-android pull request #616
Opened 2024-11-05 17:30 UTC by ndubkov-distcotech

PP-763

2024-11-14 11:49 UTC, abolfazlimahdi commented on bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/SkontoScreenContent.kt
> +    navigateToInvoiceScreen: (documentId: String, infoTextLines: List<String>) -> Unit,
[Suggestion] I think this should move upward (the optional parameter should be the last)

2024-11-14 11:50 UTC, abolfazlimahdi commented on bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/SkontoScreenContent.kt
> +    customBottomNavBarAdapter: InjectedViewAdapterInstance<SkontoNavigationBarBottomAdapter>?,
[Suggestion] I think this should move down in the parameters list

2024-11-14 11:51 UTC, abolfazlimahdi commented on bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/SkontoScreenContent.kt
> +    customBottomNavBarAdapter: InjectedViewAdapterInstance<SkontoNavigationBarBottomAdapter>?,
[Suggestion] I think this should move down in the parameters list

2024-11-14 11:52 UTC, abolfazlimahdi commented on bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/capture/skonto/SkontoScreenContent.kt
> +    modifier: Modifier = Modifier,
[Suggestion] I think this should be the last parameter in this widget.

2024-11-14 11:54 UTC, abolfazlimahdi requested changes
Code looks fine. Only in the SkontoScreenContent file, please take care of the parameter order (I commented in some sections, but there are more cases). 
The behavior is not as it was intended. The validation error show for a moment and then disappears. It should disappear with a user's action. Thank you!

2024-11-17 21:38 UTC, ndubkov-distcotech commented
This PR will be replaced by [PR#619](https://github.com/gini/gini-mobile-android/pull/619)

2024-11-17 21:38 UTC, closed without merging