feat: (bank-sdk) Add possibility to terminate bank-sdk from outer app
gini/gini-mobile-android pull request #624
Opened 2024-11-22 16:23 UTC by GeraltRiv

PM-127

2024-12-02 13:11 UTC, llevente requested changes
The logic looks okay. Only a small documentation typo needs to be fixed.

2024-12-11 14:15 UTC, GeraltRiv commented on bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/GiniBank.kt
> +     *  Kills Bank sdk and stos Gini payment flow
Fixed

2024-12-13 12:25 UTC, abolfazlimahdi approved these changes
Looks good. Thank you!

2024-12-13 12:46 UTC, obaidgini requested changes

2024-12-13 12:46 UTC, obaidgini commented on bank-sdk/sdk/src/main/java/net/gini/android/bank/sdk/GiniBank.kt
> +     *  Stops Bank sdk and stos Gini payment flow
I think this typo is still there which was pointed out by lenci, which is "stos" in this line "Stops Bank sdk and this word -> stos Gini payment flow"

2024-12-13 13:56 UTC, obaidgini approved these changes
Looks good to me now, thanks :)

2024-12-13 14:02 UTC, merged